installation failure log

diff --git a/.github/workflows/test-plugin-command.yml b/.github/workflows/test-plugin-command.yml
--- a/.github/workflows/test-plugin-command.yml
+++ b/.github/workflows/test-plugin-command.yml
@@ -74,12 +74,28 @@ jobs:
       with:
         # https://github.com/actions/setup-python
         python-version: 3.9
-        # architecture: x64  # TODO: remove if not needed
+        cache: 'pip'
 
     - name: Install plugin
       id: plugin-install
       run: |
         pipx install ${{ env.PIP_URL }} 2>&1 | tee install-output.txt
+        echo "::set-output name=failed::${PIPESTATUS[0]}"
+
+    - name: Create installation failure log
+      if: steps.plugin-install.outputs.failed == '1'
+      run: |
+        echo "JOB_OUTPUT<<EOF" >> $GITHUB_ENV
+        echo "melty-bot % pipx install ${{ env.PIP_URL }}" >> $GITHUB_ENV
+        cat install-output.txt >> $GITHUB_ENV
+        echo "EOF" >> $GITHUB_ENV
+
+    - name: Abort if installation failed
+      if: steps.plugin-install.outputs.failed == '1'
+      uses: actions/github-script@v3
+      with:
+        script: |
+            core.setFailed('Plugin installation failed')
 
     - name: Print plugin help
       id: plugin-help
@@ -107,7 +123,7 @@ jobs:
     # Generates the JOB_OUTPUT env var, accessible via '${{ env.JOB_OUTPUT }}''
     # Ref: https://trstringer.com/github-actions-multiline-strings/
     - name: Process job output
-      id: vars
+      if: steps.plugin-install.outputs.failed == '0'
       run: |
         echo "JOB_OUTPUT<<EOF" >> $GITHUB_ENV
         echo "melty-bot % ${{ env.PLUGIN_NAME }} --help" >> $GITHUB_ENV
@@ -117,7 +133,7 @@ jobs:
           echo "> - ✅ 'catalog'" >> $GITHUB_ENV
         elif grep -q -e "--properties" help-output.txt; then
           echo "> - ❌ 'catalog'" >> $GITHUB_ENV
-          echo "> - ✅ 'properties'"
+          echo "> - ✅ 'properties'" >> $GITHUB_ENV
         else
           echo "> - ❌ 'catalog'" >> $GITHUB_ENV
           echo "> - ❌ 'properties'" >> $GITHUB_ENV
@@ -142,6 +158,7 @@ jobs:
 
     - name: Append summary output
       uses: peter-evans/create-or-update-comment@v2
+      if: always()
       with:
         comment-id: ${{ github.event.inputs.comment-id }}
         body: |
@@ -170,7 +187,7 @@ jobs:
 
     - name: Add reaction (failure)
       uses: peter-evans/create-or-update-comment@v2
-      if: ${{ failure() }}
+      if: failure()
       with:
         token: ${{ secrets.ACTIONS_BOT_TOKEN }}
         repository: ${{ github.event.inputs.repository }}
